// -------------------------------------------------------------------------------------------------
//  Copyright (C) 2015-2026 Nautech Systems Pty Ltd. All rights reserved.
//  https://nautechsystems.io
//
//  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------------------------------

//! Source evidence shared by native dispatch capture and historical callbacks.
//!
//! Serialized records describe the source. They do not establish a current node phase,
//! prove a successful replay or authorize a venue command.

use anyhow::{Context, Result, ensure};
use nautilus_core::UUID4;
use serde::{Deserialize, Serialize};
use serde_json::Value;

/// A source family generated by an actual native dispatch producer.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum NativeInputSource {
    Time,
    SystemEvent,
    SystemCommand,
    ExecutionEvent,
    TradingCommand,
    DataEvent,
    DataCommand,
    ExternalMessage,
    QueryResult,
    Maintenance,
    Lifecycle,
    Reconciliation,
}

/// The immutable source installation and codec contract.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeTraceSource {
    pub schema_version: u32,
    pub node_instance: UUID4,
    pub process_incarnation: UUID4,
    pub journal_run: String,
    pub logical_run: String,
    pub configuration_digest: String,
    pub codec_profile: String,
    pub registered_profile_digest: String,
}

impl NativeTraceSource {
    /// Validates the versioned source identity without issuing runtime authority.
    ///
    /// # Errors
    /// Refuses absent, oversized or unsupported identities.
    pub fn validate(&self) -> Result<()> {
        ensure!(
            self.schema_version == 1,
            "unsupported native trace source schema"
        );
        for value in [
            &self.journal_run,
            &self.logical_run,
            &self.configuration_digest,
            &self.codec_profile,
            &self.registered_profile_digest,
        ] {
            ensure!(
                !value.is_empty() && value.len() <= 256 && !value.contains('\0'),
                "invalid native trace source identity"
            );
        }
        Ok(())
    }
}

/// The actual producer of a subsequently queued message, distinct from stack nesting.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeInputCause {
    pub process_incarnation: UUID4,
    pub journal_run: String,
    pub root_sequence: u64,
    pub input_sequence: u64,
}

/// Admission evidence carried alongside the original message through the owned FIFO.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeIngressReceipt {
    pub message_id: UUID4,
    pub channel_id: UUID4,
    pub channel_ordinal: u64,
    pub input_source: NativeInputSource,
    pub clock_anchor_wall_ns: u64,
    pub accepted_elapsed_ns: u64,
    pub accepted_wall_ns: u64,
    pub caused_by: Option<NativeInputCause>,
}

/// Wall and process-monotonic samples from one actual dispatch boundary.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeProcessingReceipt {
    pub wall_ns: u64,
    pub process_elapsed_ns: u64,
    pub ingress: Option<NativeIngressReceipt>,
}

/// A versioned read dependency captured from the actual provider used by a callback.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeReadWitness {
    pub component_id: String,
    pub profile: String,
    pub source_version: String,
    pub payload: Value,
}

/// Actual derived ingress admission, distinct from its later dequeue/processing.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeQueuedOutput {
    pub receipt: NativeIngressReceipt,
    pub payload: Value,
    pub accepted: bool,
}

/// An actual staged runner member, sealed by the native checkpoint barrier.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativePendingInput {
    pub receipt: NativeIngressReceipt,
    pub payload: Value,
    pub callback_binding: Option<Value>,
    pub timer_event: Option<Value>,
}

#[cfg(feature = "live")]
type NativeIngressEncoder = dyn Fn(NativeInputSource, &dyn std::any::Any) -> Result<Value>;
#[cfg(feature = "live")]
thread_local! { static INGRESS_ENCODER: std::cell::RefCell<Option<std::rc::Rc<NativeIngressEncoder>>> = const { std::cell::RefCell::new(None) }; }
/// Installs this actual node's strict source codec for local derived queue effects.
#[cfg(feature = "live")]
pub fn set_native_ingress_encoder(
    encode: impl Fn(NativeInputSource, &dyn std::any::Any) -> Result<Value> + 'static,
) {
    INGRESS_ENCODER.with(|current| *current.borrow_mut() = Some(std::rc::Rc::new(encode)));
}
#[cfg(feature = "live")]
pub(crate) fn encode_native_ingress(
    source: NativeInputSource,
    input: &dyn std::any::Any,
) -> Result<Value> {
    let encode = INGRESS_ENCODER
        .with(|current| {
            current
                .try_borrow()
                .ok()
                .and_then(|current| current.clone())
        })
        .context("native derived queue codec absent or busy")?;
    encode(source, input)
}

/// Correlation generated by the owner-thread native scope at actual output capture.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeOutputOrigin {
    pub source: NativeTraceSource,
    pub root_sequence: u64,
    pub input_sequence: u64,
    pub stack_parent: Option<u64>,
    pub output_ordinal: u64,
}

/// Immediate result of one actual native transport call. Success means local acceptance,
/// never a venue ACK. Historical routing consumes this receipt without invoking transport.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeTransportReceipt {
    pub client_id: String,
    pub operation: String,
    pub request: Value,
    pub outcome: std::result::Result<(), String>,
}

/// Canonical source output expectation supplied by the actual native Journal reader.
/// Capture metadata stays original; replay compares topic/payload/semantic headers
/// and suppresses a second economic append to the child Journal.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NativeHistoricalOutput {
    pub source_entry_sequence: u64,
    pub source_entry_hash: String,
    pub topic: String,
    pub payload_type: String,
    pub payload: Vec<u8>,
    pub semantic_headers: Value,
}

/// One actual registered Clock read. It supplies historical callback data only;
/// current grant deadlines and release freshness continue to use real time.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeClockRead {
    pub clock_id: UUID4,
    pub operation: String,
    pub value: Value,
}

/// Historical lifecycle data for the same original registered component. Its
/// normal Component state machine is not started/stopped by a historical hook.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct NativeComponentLifecycle {
    pub action: String,
    pub component_id: String,
}

/// One actual component callback route, recorded before its normal handler mutates.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeCallbackRoute {
    pub component_id: String,
    pub kind: String,
    pub component_state: String,
}

/// A trace record stored in the same Journal as its native outputs.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "record", deny_unknown_fields)]
pub enum NativeTraceRecord {
    Begin {
        source: NativeTraceSource,
        root_sequence: u64,
        input_sequence: u64,
        stack_parent: Option<u64>,
        input_source: NativeInputSource,
        phase: String,
        receipt: NativeProcessingReceipt,
        payload: Value,
        read_witnesses: Vec<NativeReadWitness>,
    },
    Complete {
        source: NativeTraceSource,
        root_sequence: u64,
        input_sequence: u64,
        receipt: NativeProcessingReceipt,
        output_count: u64,
        native_effects: Value,
        callbacks: Vec<NativeCallbackRoute>,
        transports: Vec<NativeTransportReceipt>,
        uuid_draws: Vec<UUID4>,
        clock_reads: Vec<NativeClockRead>,
        queued_outputs: Vec<NativeQueuedOutput>,
    },
    Abort {
        source: NativeTraceSource,
        root_sequence: u64,
        input_sequence: u64,
        reason: String,
    },
    Uncovered {
        source: NativeTraceSource,
        reason: String,
    },
}

#[cfg(feature = "live")]
pub mod scope {
    use std::{cell::RefCell, marker::PhantomData, rc::Rc};

    use anyhow::{Context, Result, ensure};

    use super::{
        NativeCallbackRoute, NativeIngressReceipt, NativeInputCause, NativeInputSource,
        NativeOutputOrigin, NativeTraceSource,
    };
    use crate::live::dst;

    #[derive(Debug)]
    struct Frame {
        epoch: u64,
        source: NativeTraceSource,
        root: u64,
        input: u64,
        parent: Option<u64>,
        output_count: u64,
        activity_at: dst::time::Instant,
        callbacks: Vec<NativeCallbackRoute>,
        transports: Vec<super::NativeTransportReceipt>,
        uuid_draws: Vec<nautilus_core::UUID4>,
        clock_reads: Vec<super::NativeClockRead>,
        queued_outputs: Vec<super::NativeQueuedOutput>,
    }

    #[derive(Debug, Default)]
    struct State {
        next_epoch: u64,
        frames: Vec<Frame>,
        failed: bool,
        receipts_enabled: bool,
        received: Option<NativeIngressReceipt>,
    }

    thread_local! {
        static CURRENT: RefCell<State> = RefCell::new(State::default());
    }

    pub(crate) fn fail() {
        CURRENT.with(|current| {
            if let Ok(mut state) = current.try_borrow_mut() {
                state.failed = true;
            }
        });
    }
    pub(crate) fn note_queued_output(output: super::NativeQueuedOutput) -> Result<()> {
        CURRENT.with(|current| {
            let mut state = current
                .try_borrow_mut()
                .context("native queue capture reentered")?;
            ensure!(!state.failed, "native queue source failed");
            let frame = state
                .frames
                .last_mut()
                .context("native queue source frame absent")?;
            ensure!(
                output.receipt.caused_by
                    == Some(NativeInputCause {
                        process_incarnation: frame.source.process_incarnation,
                        journal_run: frame.source.journal_run.clone(),
                        root_sequence: frame.root,
                        input_sequence: frame.input
                    }),
                "native derived queue cause changed"
            );
            frame.queued_outputs.push(output);
            Ok(())
        })
    }

    /// Records the actual callback route on the active source scope, if any.
    /// This does not invoke a handler or grant callback admission.
    /// # Errors
    /// Refuses a failed source or empty identity.
    pub fn note_callback(route: NativeCallbackRoute) -> Result<()> {
        CURRENT.with(|state| {
            let mut state = state
                .try_borrow_mut()
                .context("native callback scope reentered")?;
            ensure!(!state.failed, "native source callback scope failed");
            ensure!(
                !route.component_id.is_empty() && !route.kind.is_empty(),
                "native callback identity absent"
            );
            if let Some(frame) = state.frames.last_mut() {
                frame.callbacks.push(route);
            }
            Ok(())
        })
    }

    #[must_use]
    pub(crate) fn capture_active() -> bool {
        CURRENT
            .try_with(|state| {
                state
                    .try_borrow()
                    .map(|state| !state.frames.is_empty())
                    .unwrap_or(true)
            })
            .unwrap_or(true)
    }

    pub(super) fn note_uuid(uuid: nautilus_core::UUID4) -> Result<()> {
        CURRENT.with(|state| {
            let mut state = state
                .try_borrow_mut()
                .context("native UUID scope reentered")?;
            ensure!(!state.failed, "native UUID scope failed");
            if let Some(frame) = state.frames.last_mut() {
                frame.uuid_draws.push(uuid);
            }
            Ok(())
        })
    }
    pub(super) fn note_transport(receipt: super::NativeTransportReceipt) -> Result<()> {
        CURRENT.with(|state| {
            let mut state = state
                .try_borrow_mut()
                .context("native transport scope reentered")?;
            ensure!(!state.failed, "native transport scope failed");
            if let Some(frame) = state.frames.last_mut() {
                frame.transports.push(receipt);
            }
            Ok(())
        })
    }

    pub(super) fn note_clock_read(read: super::NativeClockRead) -> Result<()> {
        CURRENT.with(|state| {
            let mut state = state
                .try_borrow_mut()
                .context("native Clock source reentered")?;
            ensure!(!state.failed, "native Clock source failed");
            if let Some(frame) = state.frames.last_mut() {
                frame.clock_reads.push(read);
            }
            Ok(())
        })
    }

    /// Enables receipt tracking before the owning node starts consuming its channels.
    /// This records source admission and does not change callback or venue permissions.
    ///
    /// # Errors
    /// Refuses an already active, failed or previously consumed receipt scope.
    pub fn enable_ingress_receipts() -> Result<()> {
        CURRENT.with(|state| {
            let mut state = state
                .try_borrow_mut()
                .context("native receipt scope reentered")?;
            ensure!(
                !state.failed && !state.receipts_enabled && state.frames.is_empty(),
                "native receipt scope unavailable"
            );
            state.receipts_enabled = true;
            Ok(())
        })
    }

    /// Records the receipt physically dequeued with the actual message.
    /// Overwriting an unconsumed receipt poisons the source instead of dropping identity.
    pub fn received_ingress(receipt: Option<NativeIngressReceipt>) {
        let _ = CURRENT.try_with(|state| {
            if let Ok(mut state) = state.try_borrow_mut() {
                if !state.receipts_enabled {
                    return;
                }
                if state.received.is_some() || receipt.is_none() {
                    state.failed = true;
                }
                state.received = receipt;
            }
        });
    }

    /// Consumes only the receipt for this actual native producer.
    /// Inline mutation producers have no channel receipt and retain their real processing sample.
    ///
    /// # Errors
    /// Refuses a foreign channel, missing runner receipt, overwritten evidence or reentrancy.
    pub fn take_ingress(source: NativeInputSource) -> Result<Option<NativeIngressReceipt>> {
        CURRENT.with(|state| {
            let mut state = state
                .try_borrow_mut()
                .context("native receipt scope reentered")?;
            ensure!(!state.failed, "native receipt scope failed");
            let runner_source = matches!(
                source,
                NativeInputSource::Time
                    | NativeInputSource::SystemEvent
                    | NativeInputSource::SystemCommand
                    | NativeInputSource::ExecutionEvent
                    | NativeInputSource::TradingCommand
                    | NativeInputSource::DataEvent
                    | NativeInputSource::DataCommand
            );
            if runner_source && let Some(receipt) = state.received.take() {
                ensure!(
                    receipt.input_source == source,
                    "native receipt channel mismatch"
                );
                Ok(Some(receipt))
            } else {
                ensure!(
                    !runner_source || !state.frames.is_empty(),
                    "native runner input missing receipt"
                );
                ensure!(
                    state.received.is_none(),
                    "runner receipt replaced by inline producer"
                );
                Ok(None)
            }
        })
    }

    /// An owner-thread native capture scope. It carries no submission permission.
    #[derive(Debug)]
    pub struct NativeCaptureScope {
        epoch: u64,
        finished: bool,
        owner: PhantomData<Rc<()>>,
    }

    impl NativeCaptureScope {
        /// Binds the acknowledged native input to synchronous output capture.
        ///
        /// # Errors
        /// Refuses inconsistent nesting, a foreign source or a failed scope.
        pub fn enter(
            source: &NativeTraceSource,
            root: u64,
            input: u64,
            parent: Option<u64>,
            activity_at: dst::time::Instant,
        ) -> Result<Self> {
            source.validate()?;
            ensure!(root > 0 && input > 0, "invalid native scope frontier");
            CURRENT.with(|state| {
                let mut state = state
                    .try_borrow_mut()
                    .context("native capture scope reentered")?;
                ensure!(!state.failed, "native capture scope failed");
                match state.frames.last() {
                    Some(previous) => ensure!(
                        previous.source == *source
                            && previous.root == root
                            && Some(previous.input) == parent,
                        "native capture nesting mismatch"
                    ),
                    None => ensure!(parent.is_none(), "native capture missing stack parent"),
                }
                state.next_epoch = state
                    .next_epoch
                    .checked_add(1)
                    .context("native scope exhausted")?;
                let epoch = state.next_epoch;
                state.frames.push(Frame {
                    epoch,
                    source: source.clone(),
                    root,
                    input,
                    parent,
                    output_count: 0,
                    activity_at,
                    callbacks: Vec::new(),
                    transports: Vec::new(),
                    uuid_draws: Vec::new(),
                    clock_reads: Vec::new(),
                    queued_outputs: Vec::new(),
                });
                Ok(Self {
                    epoch,
                    finished: false,
                    owner: PhantomData,
                })
            })
        }

        /// Returns all actual Clock reads in callback and native effect capture order.
        pub fn clock_reads(&self) -> Result<Vec<super::NativeClockRead>> {
            CURRENT.with(|state| {
                let state = state
                    .try_borrow()
                    .context("native Clock source reentered")?;
                let frame = state.frames.last().context("native Clock source absent")?;
                ensure!(
                    !state.failed && frame.epoch == self.epoch,
                    "native Clock source changed"
                );
                Ok(frame.clock_reads.clone())
            })
        }

        /// Returns the actual number of captured outputs in this exact scope.
        ///
        /// # Errors
        /// Refuses a changed, nested, reentered or failed scope.
        /// Returns actual source native UUID decisions for this input.
        /// # Errors
        /// Refuses a changed source scope.
        pub fn uuid_draws(&self) -> Result<Vec<nautilus_core::UUID4>> {
            CURRENT.with(|state| {
                let state = state.try_borrow().context("native UUID scope reentered")?;
                let frame = state.frames.last().context("native UUID frame absent")?;
                ensure!(
                    !state.failed && frame.epoch == self.epoch,
                    "native UUID scope changed"
                );
                Ok(frame.uuid_draws.clone())
            })
        }
        pub fn queued_outputs(&self) -> Result<Vec<super::NativeQueuedOutput>> {
            CURRENT.with(|current| {
                let state = current
                    .try_borrow()
                    .context("native queued scope reentered")?;
                let frame = state.frames.last().context("native queued scope absent")?;
                ensure!(
                    !state.failed && frame.epoch == self.epoch,
                    "native queued scope changed"
                );
                Ok(frame.queued_outputs.clone())
            })
        }
        /// Returns actual immediate transport outcomes, separate from venue acceptance.
        /// # Errors
        /// Refuses a changed source scope.
        pub fn transports(&self) -> Result<Vec<super::NativeTransportReceipt>> {
            CURRENT.with(|state| {
                let state = state
                    .try_borrow()
                    .context("native transport scope reentered")?;
                let frame = state
                    .frames
                    .last()
                    .context("native transport frame absent")?;
                ensure!(
                    !state.failed && frame.epoch == self.epoch,
                    "native transport scope changed"
                );
                Ok(frame.transports.clone())
            })
        }

        /// Returns exact source callback order for this active input.
        /// # Errors
        /// Refuses a foreign, changed or failed scope.
        pub fn callbacks(&self) -> Result<Vec<NativeCallbackRoute>> {
            CURRENT.with(|state| {
                let state = state.try_borrow().context("native callbacks reentered")?;
                ensure!(!state.failed, "native callback scope failed");
                let frame = state
                    .frames
                    .last()
                    .context("native callback frame absent")?;
                ensure!(frame.epoch == self.epoch, "native callback frame changed");
                Ok(frame.callbacks.clone())
            })
        }

        pub fn output_count(&self) -> Result<u64> {
            CURRENT.with(|state| {
                let state = state
                    .try_borrow()
                    .context("native capture scope reentered")?;
                let frame = state.frames.last().context("native capture scope absent")?;
                ensure!(
                    !state.failed && frame.epoch == self.epoch,
                    "native capture scope changed"
                );
                Ok(frame.output_count)
            })
        }

        /// Ends only this scope after its actual durable completion acknowledgment.
        ///
        /// # Errors
        /// Refuses a stale, nested or failed scope.
        pub fn finish(mut self) -> Result<()> {
            self.output_count()?;
            CURRENT.with(|state| {
                state.borrow_mut().frames.pop();
            });
            self.finished = true;
            Ok(())
        }
    }

    impl Drop for NativeCaptureScope {
        fn drop(&mut self) {
            if !self.finished {
                let _ = CURRENT.try_with(|state| {
                    if let Ok(mut state) = state.try_borrow_mut() {
                        state.failed = true;
                        // Failed capture still releases only this guard's owned
                        // branch. Keeping a dead frame would make ordinary cleanup
                        // Clock reads attempt to append to an abandoned input.
                        // The permanent source-failure latch is never cleared.
                        if let Some(index) = state
                            .frames
                            .iter()
                            .position(|frame| frame.epoch == self.epoch)
                        {
                            state.frames.truncate(index);
                        }
                    }
                });
            }
        }
    }

    /// Returns the actual producing input for a later queued message.
    #[must_use]
    pub fn current_cause() -> Option<NativeInputCause> {
        CURRENT
            .try_with(|state| {
                state.try_borrow().ok().and_then(|state| {
                    if state.failed {
                        return None;
                    }
                    state.frames.last().map(|frame| NativeInputCause {
                        process_incarnation: frame.source.process_incarnation,
                        journal_run: frame.source.journal_run.clone(),
                        root_sequence: frame.root,
                        input_sequence: frame.input,
                    })
                })
            })
            .ok()
            .flatten()
    }

    /// Allocates correlation only at the actual native output capture point.
    ///
    /// # Errors
    /// Refuses reentrancy, overflow or a failed scope. No active scope is explicitly absent.
    pub fn next_output_origin() -> Result<Option<NativeOutputOrigin>> {
        CURRENT.with(|state| {
            let mut state = state
                .try_borrow_mut()
                .context("native output capture reentered")?;
            ensure!(!state.failed, "native output capture scope failed");
            let Some(frame) = state.frames.last_mut() else {
                return Ok(None);
            };
            frame.output_count = frame
                .output_count
                .checked_add(1)
                .context("native output ordinal exhausted")?;
            Ok(Some(NativeOutputOrigin {
                source: frame.source.clone(),
                root_sequence: frame.root,
                input_sequence: frame.input,
                stack_parent: frame.parent,
                output_ordinal: frame.output_count,
            }))
        })
    }

    /// Uses the source dispatch's private receipt for native activity bookkeeping.
    /// Real authorization and freshness clocks are unaffected.
    #[must_use]
    pub fn effective_activity_instant() -> dst::time::Instant {
        if let Some(at) = super::historical::activity_instant() {
            return at;
        }
        CURRENT
            .try_with(|state| {
                state
                    .try_borrow()
                    .ok()
                    .and_then(|state| state.frames.last().map(|frame| frame.activity_at))
            })
            .ok()
            .flatten()
            .unwrap_or_else(dst::time::Instant::now)
    }
}

/// Original component callback routing. This cannot release a node or send a venue command.
#[cfg(feature = "live")]
pub mod historical {
    use super::{
        NativeCallbackRoute, NativeReadWitness, NativeTraceRecord, NativeTransportReceipt,
    };
    use anyhow::{Context, Result, ensure};
    use std::{any::Any, cell::RefCell, rc::Rc};

    /// Preparation view for the original registered object. The source is an opaque
    /// native reader proof; installing local pubsub bindings grants no live callbacks.
    pub struct HistoricalReplayPreparation<'a> {
        source: &'a dyn Any,
        component_id: &'a str,
    }
    impl std::fmt::Debug for HistoricalReplayPreparation<'_> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.debug_struct("HistoricalReplayPreparation")
                .field("component_id", &self.component_id)
                .finish_non_exhaustive()
        }
    }
    impl<'a> HistoricalReplayPreparation<'a> {
        #[must_use]
        pub fn new(source: &'a dyn Any, component_id: &'a str) -> Self {
            Self {
                source,
                component_id,
            }
        }
        #[must_use]
        pub fn verified_source<T: Any>(&self) -> Option<&T> {
            self.source.downcast_ref()
        }
        #[must_use]
        pub const fn component_id(&self) -> &str {
            self.component_id
        }
    }

    /// Borrowed verified source for one actual original registered component callback.
    /// The source object is an opaque reader-issued proof; JSON cannot reconstruct it.
    pub struct HistoricalInputBoundary<'a> {
        verified_source: &'a dyn Any,
        input: &'a NativeTraceRecord,
        route: &'a NativeCallbackRoute,
    }
    impl std::fmt::Debug for HistoricalInputBoundary<'_> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.debug_struct("HistoricalInputBoundary")
                .field("input", &self.input)
                .field("route", &self.route)
                .finish_non_exhaustive()
        }
    }
    impl HistoricalInputBoundary<'_> {
        #[must_use]
        pub fn verified_source<T: Any>(&self) -> Option<&T> {
            self.verified_source.downcast_ref()
        }
        #[must_use]
        pub const fn input(&self) -> &NativeTraceRecord {
            self.input
        }
        #[must_use]
        pub const fn route(&self) -> &NativeCallbackRoute {
            self.route
        }
        #[must_use]
        pub fn read_witnesses(&self) -> &[NativeReadWitness] {
            match self.input {
                NativeTraceRecord::Begin { read_witnesses, .. } => read_witnesses,
                _ => &[],
            }
        }
        /// Actual original component state from this already-consumed SDK route.
        /// This read cannot change the target's physical lifecycle or callback gate.
        pub fn original_component_state(&self) -> Result<crate::enums::ComponentState> {
            use strum::IntoEnumIterator;
            crate::enums::ComponentState::iter()
                .find(|state| format!("{state:?}") == self.route.component_state)
                .context("unsupported original component state")
        }
        /// Original native admission, sealed by the SDK producer at Begin. A
        /// legacy or missing witness is unknown, never a current callback permit.
        pub fn original_callback_admitted(&self) -> Result<bool> {
            self.original_admission()?["admitted"]
                .as_bool()
                .context("original component admission is unknown")
        }
        /// The original observer exception to Component::not_running. It is
        /// source evidence, never admission for this physical recovery node.
        pub fn original_callback_is_observer(&self) -> Result<bool> {
            self.original_admission()?["observer"]
                .as_bool()
                .context("original observer registration is unknown")
        }
        fn original_admission(&self) -> Result<&serde_json::Value> {
            let witnesses = self
                .read_witnesses()
                .iter()
                .filter(|witness| witness.component_id == "native:callback_admission")
                .collect::<Vec<_>>();
            ensure!(
                witnesses.len() == 1,
                "original native callback admission unavailable"
            );
            let witness = witnesses[0];
            ensure!(
                witness.profile == "actual_registered_callback_admission.v1"
                    && witness.source_version == "native_actual_registered_admission.v1",
                "unsupported original callback admission profile"
            );
            witness.payload["components"]
                .get(&self.route.component_id)
                .context("original component admission is unknown")
        }
    }
    struct Frame {
        source: Rc<dyn Any>,
        input: NativeTraceRecord,
        routes: Vec<NativeCallbackRoute>,
        next: usize,
        transports: Vec<NativeTransportReceipt>,
        next_transport: usize,
        uuid_draws: Vec<nautilus_core::UUID4>,
        next_uuid: usize,
        clock_reads: Vec<super::NativeClockRead>,
        next_clock: usize,
        outputs: Vec<super::NativeHistoricalOutput>,
        next_output: usize,
        failure: Option<String>,
        activity_at: Option<crate::live::dst::time::Instant>,
        queued_outputs: Vec<super::NativeQueuedOutput>,
        next_queued: usize,
        native_risk_state: Option<serde_json::Value>,
    }
    thread_local! { static CURRENT: RefCell<Vec<Rc<RefCell<Frame>>>> = const { RefCell::new(Vec::new()) }; }

    /// Scoped callback routing issued by the native reader/replayer. A caller cannot use
    /// this value to construct a VerifiedNativeRoot or open the execution phase gate.
    #[must_use]
    pub struct HistoricalInputScope {
        frame: Rc<RefCell<Frame>>,
        finished: bool,
    }
    impl std::fmt::Debug for HistoricalInputScope {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.debug_struct("HistoricalInputScope")
                .field("finished", &self.finished)
                .finish_non_exhaustive()
        }
    }
    impl HistoricalInputScope {
        /// Routes only exact source callbacks; the native caller must hold its actual phase gate.
        /// # Errors
        /// Refuses nested inputs or invalid source records.
        pub fn enter(
            source: Rc<dyn Any>,
            input: NativeTraceRecord,
            routes: Vec<NativeCallbackRoute>,
            transports: Vec<NativeTransportReceipt>,
            uuid_draws: Vec<nautilus_core::UUID4>,
        ) -> Result<Self> {
            Self::enter_with_clocks(source, input, routes, transports, uuid_draws, Vec::new())
        }

        /// Includes the source's registered Clock read receipts in the same scope.
        /// # Errors
        /// Refuses an active historical scope or invalid source Begin.
        pub fn enter_with_clocks(
            source: Rc<dyn Any>,
            input: NativeTraceRecord,
            routes: Vec<NativeCallbackRoute>,
            transports: Vec<NativeTransportReceipt>,
            uuid_draws: Vec<nautilus_core::UUID4>,
            clock_reads: Vec<super::NativeClockRead>,
        ) -> Result<Self> {
            Self::enter_with_outputs(
                source,
                input,
                routes,
                transports,
                uuid_draws,
                clock_reads,
                Vec::new(),
            )
        }

        /// Routes the original verified output closure without a second cash/venue event.
        /// # Errors
        /// Refuses invalid/nested scopes or incomplete source callbacks.
        pub fn enter_with_outputs(
            source: Rc<dyn Any>,
            input: NativeTraceRecord,
            routes: Vec<NativeCallbackRoute>,
            transports: Vec<NativeTransportReceipt>,
            uuid_draws: Vec<nautilus_core::UUID4>,
            clock_reads: Vec<super::NativeClockRead>,
            outputs: Vec<super::NativeHistoricalOutput>,
        ) -> Result<Self> {
            Self::enter_with_outputs_at(
                source,
                input,
                routes,
                transports,
                uuid_draws,
                clock_reads,
                outputs,
                None,
                Vec::new(),
            )
        }

        /// Adds a private source-receipt mapping. It never changes the real clock.
        #[allow(clippy::too_many_arguments)]
        pub fn enter_with_outputs_at(
            source: Rc<dyn Any>,
            input: NativeTraceRecord,
            routes: Vec<NativeCallbackRoute>,
            transports: Vec<NativeTransportReceipt>,
            uuid_draws: Vec<nautilus_core::UUID4>,
            clock_reads: Vec<super::NativeClockRead>,
            outputs: Vec<super::NativeHistoricalOutput>,
            activity_at: Option<crate::live::dst::time::Instant>,
            queued_outputs: Vec<super::NativeQueuedOutput>,
        ) -> Result<Self> {
            ensure!(
                matches!(input, NativeTraceRecord::Begin { .. }),
                "historical input is not Begin"
            );
            let native_risk_state = match &input {
                NativeTraceRecord::Begin { read_witnesses, .. } => read_witnesses
                    .iter()
                    .find(|witness| {
                        witness.component_id == "native:risk_engine"
                            && witness.profile == "native_risk_business_state.v1"
                    })
                    .map(|witness| witness.payload["trading_state"].clone()),
                _ => None,
            };
            let frame = Rc::new(RefCell::new(Frame {
                source,
                input,
                routes,
                next: 0,
                transports,
                next_transport: 0,
                uuid_draws,
                next_uuid: 0,
                clock_reads,
                next_clock: 0,
                outputs,
                next_output: 0,
                failure: None,
                activity_at,
                queued_outputs,
                next_queued: 0,
                native_risk_state,
            }));
            CURRENT.with(|current| {
                let mut current = current
                    .try_borrow_mut()
                    .context("historical routing reentered")?;
                let new = frame
                    .try_borrow()
                    .context("historical new input reentered")?;
                if let Some(parent) = current.last() {
                    let parent = parent
                        .try_borrow()
                        .context("historical parent still borrowed")?;
                    match (&new.input, &parent.input) {
                        (
                            NativeTraceRecord::Begin {
                                source,
                                root_sequence,
                                stack_parent,
                                ..
                            },
                            NativeTraceRecord::Begin {
                                source: parent_source,
                                root_sequence: parent_root,
                                input_sequence: parent_input,
                                ..
                            },
                        ) => {
                            ensure!(
                                source == parent_source
                                    && root_sequence == parent_root
                                    && *stack_parent == Some(*parent_input)
                                    && Rc::ptr_eq(&new.source, &parent.source),
                                "historical source nesting mismatch"
                            );
                        }
                        _ => anyhow::bail!("historical parent source missing"),
                    }
                } else {
                    ensure!(
                        matches!(
                            &new.input,
                            NativeTraceRecord::Begin {
                                stack_parent: None,
                                ..
                            }
                        ),
                        "historical root parent missing"
                    );
                }
                drop(new);
                current.push(frame.clone());
                Ok(())
            })?;
            Ok(Self {
                frame,
                finished: false,
            })
        }
        /// Verifies every actual archived callback was consumed exactly once.
        /// # Errors
        /// Refuses an unsupported/mismatched/missing route or a failed hook.
        pub fn finish(mut self) -> Result<()> {
            {
                let frame = self
                    .frame
                    .try_borrow()
                    .context("historical input still borrowed")?;
                ensure!(
                    frame.failure.is_none()
                        && frame.next == frame.routes.len()
                        && frame.next_queued == frame.queued_outputs.len()
                        && frame.next_transport == frame.transports.len()
                        && frame.next_uuid == frame.uuid_draws.len()
                        && frame.next_clock == frame.clock_reads.len()
                        && frame.next_output == frame.outputs.len(),
                    "historical callback effects incomplete: {:?}",
                    frame.failure
                );
            }
            CURRENT.with(|current| {
                let mut current = current
                    .try_borrow_mut()
                    .context("historical routing reentered")?;
                ensure!(
                    current
                        .last()
                        .is_some_and(|other| Rc::ptr_eq(other, &self.frame)),
                    "historical input source changed"
                );
                current.pop();
                Ok(())
            })?;
            self.finished = true;
            Ok(())
        }
    }
    impl Drop for HistoricalInputScope {
        fn drop(&mut self) {
            if !self.finished {
                if let Ok(mut frame) = self.frame.try_borrow_mut() {
                    frame
                        .failure
                        .get_or_insert_with(|| "historical input interrupted".into());
                }
                let _ = CURRENT.try_with(|current| {
                    if let Ok(mut current) = current.try_borrow_mut() {
                        for frame in current.iter() {
                            if let Ok(mut frame) = frame.try_borrow_mut() {
                                frame.failure.get_or_insert_with(|| {
                                    "historical descendant interrupted".into()
                                });
                            }
                        }
                        if current
                            .last()
                            .is_some_and(|other| Rc::ptr_eq(other, &self.frame))
                        {
                            current.pop();
                        }
                    }
                });
            }
        }
    }
    pub(super) fn mark_failure(reason: &str) {
        let _ = CURRENT.try_with(|current| {
            if let Ok(current) = current.try_borrow() {
                if let Some(source) = current.last() {
                    if let Ok(mut source) = source.try_borrow_mut() {
                        source.failure.get_or_insert_with(|| reason.into());
                    }
                }
            }
        });
    }

    pub(super) fn next_uuid() -> Result<Option<nautilus_core::UUID4>> {
        CURRENT.with(|current| {
            let current = current
                .try_borrow()
                .context("historical UUID scope reentered")?;
            let Some(source) = current.last() else {
                return Ok(None);
            };
            let mut source = source
                .try_borrow_mut()
                .context("historical UUID scope reentered")?;
            ensure!(source.failure.is_none(), "historical UUID scope failed");
            let uuid = source
                .uuid_draws
                .get(source.next_uuid)
                .copied()
                .context("unrecorded native UUID draw")?;
            source.next_uuid += 1;
            Ok(Some(uuid))
        })
    }
    /// Compares the actual native handler's canonical output against its original
    /// source row. A match is consumed locally, never submitted to a new writer.
    pub fn output(
        topic: &str,
        payload_type: &str,
        payload: &[u8],
        headers: &serde_json::Value,
    ) -> Result<Option<u64>> {
        let outcome = CURRENT.with(|current| {
            let current = current
                .try_borrow()
                .context("historical output scope reentered")?;
            let Some(frame) = current.last() else {
                return Ok(None);
            };
            let mut frame = frame
                .try_borrow_mut()
                .context("historical output input reentered")?;
            ensure!(frame.failure.is_none(), "historical output input failed");
            let expected = frame
                .outputs
                .get(frame.next_output)
                .context("unexpected historical native output")?;
            ensure!(
                expected.topic == topic
                    && expected.payload_type == payload_type
                    && expected.payload == payload
                    && &expected.semantic_headers == headers,
                "historical native output differs from original economic/source bytes"
            );
            let sequence = expected.source_entry_sequence;
            frame.next_output += 1;
            Ok(Some(sequence))
        });
        if let Err(error) = &outcome {
            mark_failure(&format!("historical output refused: {error:#}"));
        }
        outcome
    }

    pub(super) fn clock_read(
        clock_id: nautilus_core::UUID4,
        operation: &str,
    ) -> Result<Option<serde_json::Value>> {
        CURRENT.with(|current| {
            let current = current
                .try_borrow()
                .context("historical Clock scope reentered")?;
            let Some(frame) = current.last() else {
                return Ok(None);
            };
            let mut frame = frame
                .try_borrow_mut()
                .context("historical Clock input reentered")?;
            ensure!(frame.failure.is_none(), "historical Clock input failed");
            let read = frame
                .clock_reads
                .get(frame.next_clock)
                .context("unrecorded historical Clock read")?;
            ensure!(
                read.clock_id == clock_id && read.operation == operation,
                "historical Clock owner/read order mismatch"
            );
            let value = read.value.clone();
            frame.next_clock += 1;
            Ok(Some(value))
        })
    }

    pub(super) fn transport(
        client_id: &str,
        operation: &str,
        request: &serde_json::Value,
    ) -> Result<Option<std::result::Result<(), String>>> {
        CURRENT.with(|current| {
            let current = current
                .try_borrow()
                .context("historical transport scope reentered")?;
            let Some(source) = current.last() else {
                return Ok(None);
            };
            let mut source = source
                .try_borrow_mut()
                .context("historical transport scope reentered")?;
            ensure!(
                source.failure.is_none(),
                "historical transport scope failed"
            );
            let receipt = source
                .transports
                .get(source.next_transport)
                .context("unrecorded historical transport")?;
            ensure!(
                receipt.client_id == client_id
                    && receipt.operation == operation
                    && &receipt.request == request,
                "historical native transport request mismatch"
            );
            let outcome = receipt.outcome.clone();
            source.next_transport += 1;
            Ok(Some(outcome))
        })
    }

    /// Returns whether a historical scope is present, regardless of success.
    #[must_use]
    pub fn pending_callback_route() -> Result<Option<NativeCallbackRoute>> {
        CURRENT.with(|current| {
            let frames = current
                .try_borrow()
                .context("historical route scope busy")?;
            let Some(frame) = frames.last() else {
                return Ok(None);
            };
            let frame = frame.try_borrow().context("historical route input busy")?;
            Ok(frame.routes.get(frame.next).cloned())
        })
    }

    /// Historical risk decisions read a verified source business view. The actual
    /// native RiskEngine remains Halted until a separate sealed current release.
    pub(super) fn risk_state() -> Result<Option<serde_json::Value>> {
        CURRENT.with(|current| {
            let frames = current.try_borrow().context("historical risk scope busy")?;
            let Some(frame) = frames.last() else {
                return Ok(None);
            };
            let frame = frame.try_borrow().context("historical risk input busy")?;
            Ok(Some(
                frame
                    .native_risk_state
                    .clone()
                    .context("historical native risk source witness absent")?,
            ))
        })
    }
    pub(super) fn set_risk_state(value: serde_json::Value) -> Result<bool> {
        CURRENT.with(|current| {
            let frames = current.try_borrow().context("historical risk scope busy")?;
            if frames.is_empty() {
                return Ok(false);
            }
            for frame in frames.iter() {
                let mut frame = frame
                    .try_borrow_mut()
                    .context("historical risk input busy")?;
                ensure!(
                    frame.native_risk_state.is_some(),
                    "historical native risk source absent"
                );
                frame.native_risk_state = Some(value.clone());
            }
            Ok(true)
        })
    }

    /// Consumes the exact old local queue effect without enqueueing it twice.
    pub(crate) fn queued(
        source: super::NativeInputSource,
        payload: &serde_json::Value,
    ) -> Result<Option<bool>> {
        CURRENT.with(|current| {
            let frames = current
                .try_borrow()
                .context("historical queue routing busy")?;
            let Some(frame) = frames.last() else {
                return Ok(None);
            };
            let mut frame = frame
                .try_borrow_mut()
                .context("historical queue input busy")?;
            let output = frame
                .queued_outputs
                .get(frame.next_queued)
                .context("historical queued effect absent")?;
            ensure!(
                output.receipt.input_source == source && output.payload == *payload,
                "historical queued intent changed source or payload"
            );
            let accepted = output.accepted;
            frame.next_queued += 1;
            Ok(Some(accepted))
        })
    }

    pub(super) fn activity_instant() -> Option<crate::live::dst::time::Instant> {
        CURRENT
            .try_with(|current| {
                current.try_borrow().ok().and_then(|frames| {
                    frames.last().and_then(|frame| {
                        frame.try_borrow().ok().and_then(|frame| frame.activity_at)
                    })
                })
            })
            .ok()
            .flatten()
    }

    pub fn active() -> bool {
        CURRENT
            .try_with(|current| {
                current
                    .try_borrow()
                    .map(|value| !value.is_empty())
                    .unwrap_or(true)
            })
            .unwrap_or(true)
    }

    /// Invokes the hook on the actual registered object before normal indicators/lifecycle effects.
    /// A failed route remains consumed only as failure evidence; normal callbacks stay closed.
    pub fn dispatch_if_active(
        component_id: &str,
        kind: &str,
        callback: impl FnOnce(&HistoricalInputBoundary<'_>) -> Result<()>,
    ) -> bool {
        let source = CURRENT
            .try_with(|current| {
                current
                    .try_borrow()
                    .ok()
                    .and_then(|value| value.last().cloned())
            })
            .ok()
            .flatten();
        let Some(source) = source else {
            // Busy/failed historical state never falls through to ordinary callbacks.
            return active();
        };
        let outcome = (|| -> Result<()> {
            let (verified_source, input, route) = {
                let mut frame = source
                    .try_borrow_mut()
                    .context("historical callback reentered")?;
                ensure!(
                    frame.failure.is_none(),
                    "historical callback already failed"
                );
                let route = frame
                    .routes
                    .get(frame.next)
                    .context("unexpected historical callback")?
                    .clone();
                ensure!(
                    route.component_id == component_id && route.kind == kind,
                    "historical callback order/owner mismatch"
                );
                frame.next += 1;
                (frame.source.clone(), frame.input.clone(), route)
            };
            let boundary = HistoricalInputBoundary {
                verified_source: verified_source.as_ref(),
                input: &input,
                route: &route,
            };
            callback(&boundary)
        })();
        if let Err(error) = outcome {
            if let Ok(mut frame) = source.try_borrow_mut() {
                frame.failure.get_or_insert_with(|| format!("{error:#}"));
            }
        }
        true
    }
}

/// Captures normal registered Clock reads or returns the verified original read to
/// historical business callbacks. This does not change AtomicTime or freshness checks.
/// # Panics
/// A changed read poisons the scope and is contained by the native replay owner.
pub fn native_clock_read<T: Serialize + serde::de::DeserializeOwned>(
    clock_id: UUID4,
    operation: &str,
    actual: T,
) -> T {
    #[cfg(feature = "live")]
    {
        let historical = historical::clock_read(clock_id, operation).unwrap_or_else(|error| {
            historical::mark_failure("historical Clock read refused");
            panic!("historical Clock read refused: {error:#}")
        });
        if let Some(value) = historical {
            return serde_json::from_value(value)
                .expect("verified Clock read has unsupported value type");
        }
        if scope::capture_active() {
            scope::note_clock_read(NativeClockRead {
                clock_id,
                operation: operation.into(),
                value: serde_json::to_value(&actual).expect("native Clock read encoding failed"),
            })
            .expect("native Clock read recording failed");
        }
    }
    #[cfg(not(feature = "live"))]
    let _ = (clock_id, operation);
    actual
}

/// Generates a native event UUID, retaining its actual source decision for historical replay.
/// Outside an owner-thread native scope it preserves ordinary UUID generation.
/// # Panics
/// Panics on an absent/changed historical decision; the node replay owner must fence and retain evidence.
#[must_use]
pub fn native_event_uuid() -> UUID4 {
    #[cfg(feature = "live")]
    if let Some(uuid) = historical::next_uuid().expect("native historical UUID decision failed") {
        return uuid;
    }
    let uuid = UUID4::new();
    #[cfg(feature = "live")]
    if scope::capture_active() {
        scope::note_uuid(uuid).expect("native source UUID recording failed");
    }
    uuid
}

/// Invokes actual normal transport once, or consumes its verified original immediate result
/// inside historical routing. Historical success never calls `transport` and is not a venue ACK.
/// # Errors
/// Refuses unrecorded/changed requests, encoding failures and original local rejection.
pub fn native_transport<T: Serialize>(
    client_id: &str,
    operation: &str,
    request: &T,
    transport: impl FnOnce() -> Result<()>,
) -> Result<()> {
    #[cfg(feature = "live")]
    {
        if !scope::capture_active() && !historical::active() {
            return transport();
        }
        let request = serde_json::to_value(request)?;
        let original = historical::transport(client_id, operation, &request).map_err(|error| {
            historical::mark_failure(&format!("historical transport refused: {error:#}"));
            error
        })?;
        if let Some(outcome) = original {
            return outcome.map_err(anyhow::Error::msg);
        }
        let outcome = transport();
        let recorded = outcome
            .as_ref()
            .map(|_| ())
            .map_err(|error| format!("{error:#}"));
        ensure!(
            recorded
                .as_ref()
                .err()
                .is_none_or(|reason| reason.len() <= 4096 && !reason.contains('\0')),
            "native transport rejection cannot be safely archived"
        );
        scope::note_transport(NativeTransportReceipt {
            client_id: client_id.into(),
            operation: operation.into(),
            request,
            outcome: recorded,
        })?;
        outcome
    }
    #[cfg(not(feature = "live"))]
    {
        let _ = (client_id, operation, request);
        transport()
    }
}

/// Reports only scoped historical callback routing, never execution permission.
#[must_use]
pub fn historical_active() -> bool {
    #[cfg(feature = "live")]
    {
        historical::active()
    }
    #[cfg(not(feature = "live"))]
    {
        false
    }
}

/// Records an unsupported historical effect; a logged callback error cannot become completion.
pub fn historical_failure(reason: &str) {
    #[cfg(feature = "live")]
    {
        historical::mark_failure(reason);
        if scope::capture_active() {
            scope::fail();
        }
    }
    #[cfg(not(feature = "live"))]
    let _ = reason;
}

/// Returns only the scoped source risk state; it cannot alter live admission.
pub fn native_risk_state<T: Serialize + serde::de::DeserializeOwned + Copy>(actual: T) -> T {
    #[cfg(feature = "live")]
    if let Some(value) = historical::risk_state().expect("historical native risk view missing") {
        return serde_json::from_value(value).expect("historical native risk state malformed");
    }
    actual
}
/// Updates the historical business mirror, never the actual live risk state.
pub fn set_native_historical_risk_state<T: Serialize>(value: T) -> bool {
    #[cfg(feature = "live")]
    {
        return historical::set_risk_state(
            serde_json::to_value(value).expect("risk state encoding failed"),
        )
        .expect("historical native risk view failed");
    }
    #[cfg(not(feature = "live"))]
    {
        let _ = value;
        false
    }
}
